spring:
  application:
    name: xiangyun-consult

  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
        import-check:
          enabled: false
  autoconfigure:
    exclude:
      - com.alibaba.cloud.nacos.NacosConfigAutoConfiguration
      - com.alibaba.cloud.nacos.discovery.NacosDiscoveryClientAutoConfiguration
      - com.alibaba.cloud.sentinel.SentinelAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8082

logging:
  level:
    com.xiangyun: DEBUG
